/**
 * Unvara model catalog (catalog/catalog.json). Generated by script/catalog/build.ts from catalog/sources.yaml;
 * a snapshot ships with the app and a newer one can be fetched from the repo without an app release.
 */
import type { ModelShape } from "./fit"

export const CATALOG_SCHEMA_VERSION = 1

export type CatalogFile = { name: string; size: number; sha256: string }

export type CatalogQuant = {
  quant: string
  /** One file, or the shards of a split GGUF in order. */
  files: CatalogFile[]
  size: number
}

export type CatalogModel = {
  id: string
  name: string
  family: string
  repo: string
  publisher: string
  /** How refusals were removed; null for official releases. */
  uncensored: "abliterated" | "heretic" | "finetune" | null
  base?: string
  description: { en: string; ru: string }
  tags: string[]
  capabilities: { tools: boolean; vision: boolean; reasoning: boolean }
  license?: string
  arch: string
  paramsTotal: number
  /** MoE: parameters used per token. */
  paramsActive?: number
  contextMax: number
  shape: ModelShape
  quants: CatalogQuant[]
  recommendedQuant: string
  /** Vision projector that must be downloaded alongside any quant. */
  mmproj?: CatalogFile
  sampling?: { temperature?: number; topK?: number; topP?: number; minP?: number }
  downloads: number
  updatedAt: string
}

export type Catalog = {
  schemaVersion: number
  minAppVersion: string
  generatedAt: string
  models: CatalogModel[]
}

export function downloadUrl(repo: string, file: string, mirror = "https://huggingface.co") {
  return `${mirror}/${repo}/resolve/main/${file.split("/").map(encodeURIComponent).join("/")}`
}
